volumes:
  postgres_data:
  elasticsearch_data:

networks:
  projectile_net:
    name: projectile_net

services:
  db:
    container_name: projectile_db
    image: postgres:16
    env_file:
      - .env
    environment: # for explicitness over .env
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
    networks:
      - projectile_net

  pgbouncer:
    container_name: projectile_pgbouncer
    image: edoburu/pgbouncer:latest
    ports:
      - "6432:6432"
    volumes:
      - ../db/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ../db/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
        db:
          condition: service_healthy
    networks:
      - projectile_net

  redis:
    container_name: projectile_redis
    image: redis:8.4-alpine
    ports:
      - "6379:6379"
    networks:
      - projectile_net

  elasticsearch:
    container_name: projectile_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    command: > # to run ES in the foreground and log to stdout
      bash -c "elasticsearch > /usr/share/elasticsearch/logs/elastic.log 2>&1"
    environment:
      - discovery.type=${ELASTICSEARCH_DISCOVERY_TYPE}
      - xpack.security.enabled=${ELASTICSEARCH_SECURITY_ENABLED}
      - bootstrap.memory_lock=${ELASTICSEARCH_MEMORY_LOCK}
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - projectile_net
